--!strict

return {
	King = {
		PrimaryColor = Color3.fromRGB(235, 195, 5),
		SecondaryColor = Color3.fromRGB(155, 125, 5),
	},

	Judge = {
		PrimaryColor = Color3.fromRGB(155, 35, 225),
		SecondaryColor = Color3.fromRGB(90, 15, 145),
	},

	Landlord = {
		PrimaryColor = Color3.fromRGB(195, 245, 105),
		SecondaryColor = Color3.fromRGB(125, 155, 65),
	},

	Enforcer = {
		PrimaryColor = Color3.fromRGB(45, 55, 175),
		SecondaryColor = Color3.fromRGB(25, 35, 115),
	},

	Owner = {
		PrimaryColor = Color3.fromRGB(205, 15, 15),
		SecondaryColor = Color3.fromRGB(125, 10, 10),
	},

	Host = {
		PrimaryColor = Color3.fromRGB(235, 195, 5),
		SecondaryColor = Color3.fromRGB(155, 125, 5),
	},
}
